server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cotrip?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
